# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 21:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20150916_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='group_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophasebase.OphaseCategory', verbose_name='Gruppenkategorie'),
        ),
    ]
