# Generated by Django 2.0.9 on 2018-10-05 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20170209_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examroom',
            name='room',
            field=models.OneToOneField(limit_choices_to={'type': 'HS'}, on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Room', verbose_name='Raum'),
        ),
    ]
