# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_remove_student_want_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='e-mail address'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='prename',
            field=models.CharField(max_length=50, verbose_name='first name'),
        ),
    ]
