# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_auto_20160529_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='student_registration_enabled',
            field=models.BooleanField(default=False, verbose_name='Studenten Registrierung aktiv'),
        ),
    ]
