# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20161005_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='want_exam',
            field=models.BooleanField(default=False, help_text='Die Klausur ist eine Simulation einer Uniklausur, um die Unteschiede zwischen einer Schul- und einer Universitätsklausr zu zeigen. Abgefragt werden hauptsächlich Informationen aus der Ophase. Es ist nicht verpflichtend die Klausur zu bestehen.', verbose_name='Klausur mitschreiben?'),
        ),
    ]
