# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20161010_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='want_exam',
            field=models.BooleanField(default=False, help_text='Die Klausur ist eine Simulation einer Uniklausur, um die Unterschiede zwischen einer Schul- und einer Universitätsklausur zu zeigen. Abgefragt werden hauptsächlich Informationen aus der Ophase. Es ist nicht verpflichtend, die Klausur zu bestehen.', verbose_name='Klausur mitschreiben?'),
        ),
    ]
