# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0004_auto_20170209_2025'),
        ('students', '0011_auto_20161010_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='categories',
            field=models.ManyToManyField(blank=True, to='ophasebase.OphaseCategory', verbose_name='Kategorie(n) zu der/den der Newsletter gehört'),
        ),
    ]
