# Generated by Django 2.0.9 on 2018-10-05 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_newsletter_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='newsletters',
            field=models.ManyToManyField(blank=True, help_text='Welche Newsletter willst du abonieren (optional)?', limit_choices_to={'active': True}, to='students.Newsletter', verbose_name='Newsletter'),
        ),
    ]
