# Generated by Django 2.2 on 2019-04-05 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0013_auto_20181005_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='want_exam',
            field=models.BooleanField(blank=True, default=False, help_text='Die Klausur ist eine Simulation einer Uniklausur, um die Unterschiede zwischen einer Schul- und einer Universitätsklausur zu zeigen. Abgefragt werden hauptsächlich Informationen aus der Ophase. Es ist nicht verpflichtend, die Klausur zu bestehen.', verbose_name='Klausur mitschreiben?'),
        ),
    ]
