# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helpdesk_phone_number', models.CharField(max_length=50)),
                ('vorkurs_start_date', models.DateField()),
                ('vorkurs_end_date', models.DateField()),
                ('vorkurs_url', models.CharField(max_length=2000)),
                ('vorkurs_forum_url', models.CharField(max_length=2000)),
                ('vorkurs_slides_url', models.CharField(max_length=2000)),
                ('accounts_url', models.CharField(max_length=2000)),
                ('einforz_url', models.CharField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Einstellungen',
                'verbose_name_plural': 'Einstellungen',
            },
        ),
    ]
