# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-15 13:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('BSC', 'Bachelor'), ('MSC', 'Master Deutsch'), ('DSS', 'Distributed Software Systems')], max_length=3, unique=True, verbose_name='Abschluss')),
                ('image', models.ImageField(upload_to='website/schedule/', verbose_name='Stundenplan Bild')),
                ('stand', models.DateField(verbose_name='Stand des Stundenplans')),
            ],
            options={
                'verbose_name_plural': 'Stundenpläne',
                'verbose_name': 'Stundenplan',
            },
        ),
    ]
