# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160816_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='accounts_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='einforz_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='vorkurs_forum_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='vorkurs_slides_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='vorkurs_url',
            field=models.URLField(),
        ),
    ]
