# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20160928_0259'),
    ]

    operations = [
        migrations.CreateModel(
            name='OInforz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('BSC', 'Bachelor'), ('MSC', 'Master Deutsch'), ('DSS', 'Distributed Software Systems')], max_length=3, unique=True, verbose_name='Abschluss')),
                ('file', models.FileField(storage=website.models.OverwriteStorage(), upload_to=website.models.OInforz.fixedname_upload_to, verbose_name='OInforz PDF')),
                ('stand', models.DateField(verbose_name='Stand des OInforzes')),
            ],
            options={
                'verbose_name': 'OInforz',
                'verbose_name_plural': 'OInforze',
            },
        ),
    ]
