# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0005_auto_20170212_1633'),
        ('website', '0006_oinforz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='degree',
        ),
        migrations.AddField(
            model_name='schedule',
            name='category',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ophasebase.OphaseCategory', verbose_name='Ophasen Kategorie'),
            preserve_default=False,
        ),
    ]
