# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 15:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0007_auto_20170215_1416'),
        ('website', '0006_oinforz'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_image', models.ImageField(storage=website.models.OverwriteStorage(), upload_to=website.models.CategoryDetails.fixedname_upload_to, verbose_name='Stundenplan Bild', null=True, blank=True)),
                ('schedule_last_modified', models.DateField(auto_now=True, verbose_name='Stand des Stundenplans')),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='website', to='ophasebase.OphaseCategory')),
            ],
            options={
                'verbose_name': 'Webseitendetails für Kategorie',
                'verbose_name_plural': 'Webseitendetails für Kategorien',
            },
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
        migrations.RenameField(
            model_name='oinforz',
            old_name='stand',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='oinforz',
            old_name='degree',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='oinforz',
            name='name',
            field=models.CharField(default='', max_length=25, verbose_name='Abschluss'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categorydetails',
            name='oinforz',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='website.OInforz', verbose_name='OInforz', blank=True),
        ),
    ]
