# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_person_orga_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=75, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='prename',
            field=models.CharField(max_length=60, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='why_participate',
            field=models.TextField(verbose_name='Warum möchtest du bei der Ophase mitmachen?'),
        ),
    ]
