# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_auto_20160228_1914'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupcategory',
            options={'ordering': ['label'], 'verbose_name': 'Gruppenkategorie', 'verbose_name_plural': 'Gruppenkategorien'},
        ),
        migrations.AlterModelOptions(
            name='helperjob',
            options={'ordering': ['label'], 'verbose_name': 'Helferjob', 'verbose_name_plural': 'Helferjobs'},
        ),
        migrations.AlterModelOptions(
            name='orgajob',
            options={'ordering': ['label'], 'verbose_name': 'Orgajob', 'verbose_name_plural': 'Orgajobs'},
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='helperjob',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='helperjob',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Bezeichnung'),
        ),
        migrations.AlterField(
            model_name='orgajob',
            name='description',
            field=models.TextField(verbose_name='Beschreibung'),
        ),
        migrations.AlterField(
            model_name='orgajob',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Bezeichnung'),
        ),
    ]
