# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 18:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_auto_20160530_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dress_size',
            field=models.ForeignKey(blank=True, help_text='Mitwirkende bekommen T-Shirts um sie besser zu erkennen. Damit dein T-Shirt passt brauchen wir deine Größe.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.DressSize', verbose_name='Kleidergröße'),
        ),
        migrations.AlterField(
            model_name='person',
            name='tutor_for',
            field=models.ForeignKey(blank=True, help_text='Erstsemester welches Studiengangs möchtest du als Tutor betreuen?', null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.GroupCategory', verbose_name='Tutor für'),
        ),
    ]
