# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20160711_2000'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DressSize',
        ),
        migrations.RemoveField(
            model_name='person',
            name='dress_size',
        ),
    ]
