# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_auto_20160606_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcategory',
            name='max_threshold',
            field=models.IntegerField(blank=True, help_text='Sobald diese Anzahl Tutoren angemeldet sind, wird die Anmeldung für diese Gruppe automatisch geschlossen.', null=True, verbose_name='Harte Maximalanzahl'),
        ),
        migrations.AlterField(
            model_name='groupcategory',
            name='warning_threshold',
            field=models.IntegerField(blank=True, help_text='Sobald diese Anzahl Tutoren angemeldet sind, wird eine Warnung bei der Registrierung angezeigt.', null=True, verbose_name='Anzahl bis Warnung'),
        ),
    ]
