# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20160913_1925'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stafffiltergroup',
            options={'ordering': ['name'], 'verbose_name': 'Staff Filtergruppe', 'verbose_name_plural': 'Staff Filtergruppen'},
        ),
        migrations.AlterField(
            model_name='attendance',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Kommentar'),
        ),
    ]
