# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-25 01:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0008_auto_20160822_1623'),
        ('staff', '0009_auto_20160606_1607'),
    ]

    operations = [
    ]
