# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 16:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_auto_20160914_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stafffiltergroup',
            name='is_tutor',
        ),
    ]
