# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-13 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0010_auto_20160913_1937'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set([('event', 'person')]),
        ),
    ]
