# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0003_auto_20160825_1424'),
        ('staff', '0010_remove_stafffiltergroup_is_tutor'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceevent',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Room', verbose_name='Raum'),
        ),
        migrations.AlterField(
            model_name='stafffiltergroup',
            name='tutor_for_all',
            field=models.BooleanField(default=False, help_text='Soll der Filter auf alle Tutorengruppen zutreffen (sonst spezifizieren).', verbose_name='Alle Tutorenkategorien?'),
        ),
    ]
