# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-14 17:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0011_auto_20160914_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Room', verbose_name='Raum'),
        ),
    ]
