# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 16:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0012_auto_20160914_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='phone_status',
            field=models.CharField(choices=[('x', 'Nicht angerufen'), ('n', 'Angerufen, nicht erreicht'), ('e', 'Angerufen, erreicht')], default='x', max_length=1, verbose_name='Telefoniestatus'),
        ),
    ]
