# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0013_attendance_phone_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='phone_status',
            field=models.CharField(choices=[('x', 'nicht angerufen'), ('n', 'angerufen + nicht erreicht'), ('e', 'angerufen + erreicht')], default='x', max_length=1, verbose_name='Telefoniestatus'),
        ),
    ]
