# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0014_auto_20161011_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('x', 'Nicht anwesend'), ('a', 'Anwesend'), ('v', 'Anwesend, verspätet'), ('e', 'Entschuldigt')], default='x', max_length=1, verbose_name='Status'),
        ),
    ]
