# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0004_auto_20170201_1530'),
        ('staff', '0015_auto_20161012_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperjob',
            name='categories',
            field=models.ManyToManyField(blank=True, to='ophasebase.OphaseCategory', verbose_name='Kategorie(n) zu der/den der Job gehört'),
        ),
        migrations.AddField(
            model_name='orgajob',
            name='categories',
            field=models.ManyToManyField(blank=True, to='ophasebase.OphaseCategory', verbose_name='Kategorie(n) zu der/den der Job gehört'),
        ),
    ]
