# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0004_auto_20170209_2025'),
        ('exam', '0003_auto_20170209_2025'),
        ('staff', '0015_auto_20161012_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='helperjob',
            name='categories',
            field=models.ManyToManyField(blank=True, to='ophasebase.OphaseCategory', verbose_name='Kategorie(n) zu der/den der Job gehört'),
        ),
        migrations.AddField(
            model_name='orgajob',
            name='categories',
            field=models.ManyToManyField(blank=True, to='ophasebase.OphaseCategory', verbose_name='Kategorie(n) zu der/den der Job gehört'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='required_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.StaffFilterGroup', verbose_name='Filterkriterium: Wer muss anwesend sein?'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophasebase.Room', verbose_name='Raum'),
        ),
        migrations.RemoveField(
            model_name='person',
            name='tutor_for',
        ),
        migrations.AddField(
            model_name='person',
            name='tutor_for',
            field=models.ForeignKey(blank=True,
                                    help_text='Erstsemester welches Studiengangs möchtest du als Tutor betreuen?',
                                    null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='ophasebase.OphaseCategory', verbose_name='Tutor für'),
        ),
        migrations.RemoveField(
            model_name='settings',
            name='group_categories_enabled',
        ),
        migrations.AddField(
            model_name='settings',
            name='group_categories_enabled',
            field=models.ManyToManyField(to='ophasebase.OphaseCategory',
                                         verbose_name='Freigeschaltete Kleingruppenkategorien'),
        ),
        migrations.RemoveField(
            model_name='stafffiltergroup',
            name='tutor_for',
        ),
        migrations.AddField(
            model_name='stafffiltergroup',
            name='tutor_for',
            field=models.ManyToManyField(blank=True, help_text='Welche Tutorengruppen sollen einbezogen werden?',
                                         to='ophasebase.OphaseCategory', verbose_name='Tutor für'),
        ),
        migrations.RemoveField(
            model_name='tutorgroup',
            name='group_category',
        ),
        migrations.AddField(
            model_name='tutorgroup',
            name='group_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophasebase.OphaseCategory',
                                    verbose_name='Gruppenkategorie', null=True, blank=False),
        ),
        migrations.DeleteModel(
            name='GroupCategory',
        ),
    ]
