# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0016_auto_20170209_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorgroup',
            name='group_category',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='ophasebase.OphaseCategory', verbose_name='Gruppenkategorie'),
            preserve_default=False,
        ),
    ]
