# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 17:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0017_auto_20170202_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendanceevent',
            name='required_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.StaffFilterGroup', verbose_name='Filterkriterium: Wer muss anwesend sein?'),
        ),
        migrations.AlterField(
            model_name='attendanceevent',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophasebase.Room', verbose_name='Raum'),
        ),
    ]
