# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_person_tutor_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='tutor_experience',
            field=models.PositiveSmallIntegerField(blank=True, default=0, help_text='Wie oft warst du bereits Ophasentutor', null=True, verbose_name='Anzahl Tutorentätigkeiten'),
        ),
    ]
