# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 17:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_person_tutor_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendanceevent',
            name='ophase',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='required_for',
        ),
        migrations.RemoveField(
            model_name='attendanceevent',
            name='room',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='plan.TimeSlot', verbose_name='Anwesenheitstermin'),
        ),
        migrations.DeleteModel(
            name='AttendanceEvent',
        ),
    ]
