# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_auto_20170526_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelperSelectedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('status', models.CharField(choices=[('i', 'Interessiert'), ('e', 'Eingeteilt'), ('n', 'Nicht eingeteilt')], default='i', max_length=1, verbose_name='Status')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.HelperJob', verbose_name='Job')),
            ],
            options={
                'verbose_name_plural': 'Gewählte Helferjobs',
                'ordering': ['job', 'status', 'person'],
                'verbose_name': 'Gewählter Helferjob',
            },
        ),
        migrations.CreateModel(
            name='OrgaSelectedJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('status', models.CharField(choices=[('i', 'Interessiert'), ('o', 'Orga'), ('c', 'Co-Orga'), ('n', 'Nicht eingeteilt')], default='i', max_length=1, verbose_name='Status')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.OrgaJob', verbose_name='Job')),
            ],
            options={
                'verbose_name_plural': 'Gewählte Helferjobs',
                'ordering': ['job', 'status', 'person'],
                'verbose_name': 'Gewählter Helferjob',
            },
        ),
        migrations.RemoveField(
            model_name='person',
            name='helper_jobs',
        ),
        migrations.RemoveField(
            model_name='person',
            name='orga_jobs',
        ),
        migrations.AddField(
            model_name='orgaselectedjob',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Person', verbose_name='Person'),
        ),
        migrations.AddField(
            model_name='helperselectedjob',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Person', verbose_name='Person'),
        ),
    ]
