# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-02 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0020_auto_20170702_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='helper_jobs',
            field=models.ManyToManyField(blank=True, help_text='Bei welchen Aufgaben kannst du dir vorstellen zu helfen?', related_name='person_helperjobs', through='staff.HelperSelectedJob', to='staff.HelperJob', verbose_name='Helferaufgaben'),
        ),
        migrations.AddField(
            model_name='person',
            name='orga_jobs',
            field=models.ManyToManyField(blank=True, help_text='Welche Orgaaufgaben kannst du dir vorstellen zu übernehmen?', related_name='person_orgajobs', through='staff.OrgaSelectedJob', to='staff.OrgaJob', verbose_name='Orgaaufgaben'),
        ),
    ]
