# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 22:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0021_auto_20170702_2133'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orgaselectedjob',
            options={'ordering': ['job', 'status', 'person'], 'verbose_name': 'Gewählter Orgajob', 'verbose_name_plural': 'Gewählte Orgajobs'},
        ),
    ]
