# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0019_auto_20170410_1946'),
        ('staff', '0022_auto_20170706_0002'),
    ]

    operations = [
    ]
