# Generated by Django 3.1.6 on 2021-02-07 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0008_auto_20190226_1853'),
        ('staff', '0026_person_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='person',
            unique_together={('ophase', 'email')},
        ),
        migrations.RemoveField(
            model_name='person',
            name='tuid',
        ),
    ]
