# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0003_settings_orga_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Eingetragen am'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Verändert am'),
        ),
    ]
