# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshops', '0004_auto_20160711_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='description',
            field=models.TextField(help_text='Eine kurze Beschreibung für OInforz und Aushänge um was es geht und was die Teilnehmer erwartet.', verbose_name='Beschreibungstext'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='remarks',
            field=models.TextField(blank=True, help_text='Sonstige Informationen für den Orga', verbose_name='Anmerkungen'),
        ),
    ]
