# Generated by Django 2.2.3 on 2019-07-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_group', models.CharField(max_length=100, verbose_name='Externer Gruppenname')),
                ('django_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Django Gruppe')),
            ],
            options={
                'verbose_name': 'Gruppen-Synchronization',
                'verbose_name_plural': 'Gruppen-Synchronizationen',
            },
        ),
    ]
