#!/bin/bash
# perform necessary actions to update an instance of pyophase

set -e

# only source the virtual env if we are not already in it
if [ -z ${VIRTUAL_ENV+x} ]; then
    source venv/bin/activate
fi

# set environment variable when we want to update a production instance
if [ "$1" = "--prod" ]; then
    export DJANGO_SETTINGS_MODULE=pyophase.settings_production
fi

git pull
npm install
if [ "$1" = "--prod" ]; then
    pip install -r requirements/production.txt
    ./manage.py collectstatic --noinput
else
    pip install -r requirements/development.txt
fi
./manage.py compilemessages  --locale='de' --locale='en'
./manage.py migrate
touch pyophase/wsgi.py
