# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0005_auto_20160228_1914'),
        ('ophasebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Termin')),
                ('duration', models.DurationField(verbose_name='Dauer')),
                ('min_places', models.IntegerField(verbose_name='Min. Places')),
                ('kommentar', models.TextField(verbose_name='Kommentar')),
                ('color', models.TextField(verbose_name='Farbe')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Room', verbose_name='Raum')),
                ('room_preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_preference', to='ophasebase.Room', verbose_name='Room Preference')),
                ('zielgruppe', models.ManyToManyField(to='staff.GroupCategory', verbose_name='Zielgruppe')),
            ],
            options={
                'verbose_name_plural': 'Termine',
                'ordering': ['kommentar', 'duration', 'room', 'start_time'],
                'verbose_name': 'Termin',
            },
        ),
    ]
