# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(max_length=7, verbose_name='Farbe'),
        ),
    ]
