# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oplan', '0002_auto_20160314_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#999999', max_length=7, verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='event',
            name='min_places',
            field=models.IntegerField(default=-1, verbose_name='Min. Places'),
        ),
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Room', verbose_name='Raum'),
        ),
        migrations.AlterField(
            model_name='event',
            name='room_preference',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_preference', to='ophasebase.Room', verbose_name='Room Preference'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Termin'),
        ),
    ]
