# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0002_auto_20160314_1429'),
        ('oplan', '0003_auto_20160314_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomOpening',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Termin')),
                ('duration', models.DurationField(verbose_name='Dauer')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'OK (Reserved)'), (2, 'Blocked by other event')])),
                ('kommentar', models.TextField(verbose_name='Kommentar')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Room', verbose_name='Raum')),
            ],
            options={
                'verbose_name': 'Raumfrei',
            },
        ),
        migrations.AlterField(
            model_name='event',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Room', verbose_name='Raum'),
        ),
        migrations.AlterField(
            model_name='event',
            name='room_preference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_preference', to='ophasebase.Room', verbose_name='Room Preference'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Termin'),
        ),
    ]
