# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_type_additional_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Color', verbose_name='Farbe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.Person', verbose_name='Person'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Size', verbose_name='Größe'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothing.Type', verbose_name='Art'),
        ),
    ]
