# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_auto_20160822_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothing_ordering_enabled', models.BooleanField(default=False, verbose_name='Kleiderbestellung aktiv')),
            ],
            options={
                'verbose_name_plural': 'Einstellungen',
                'verbose_name': 'Einstellungen',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='additional',
            field=models.BooleanField(verbose_name='Selbst bezahltes Kleidungsstück'),
        ),
        migrations.AlterField(
            model_name='type',
            name='additional_only',
            field=models.BooleanField(default=False, verbose_name='Nur als selbst bezahltes Kleidungsstück möglich'),
        ),
    ]
