# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-30 12:43
from __future__ import unicode_literals

from django.db import migrations, models

from clothing.models import Size

def forwards_func(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    # Set size_sortable for all exsisting sizes
    for size in Size.objects.using(db_alias).all():
        size.save()

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0005_auto_20160829_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ('size_sortable', 'size'), 'verbose_name': 'Größe', 'verbose_name_plural': 'Größen'},
        ),
        migrations.AddField(
            model_name='size',
            name='size_sortable',
            field=models.PositiveSmallIntegerField(default=0, help_text='Dieser Wert wird automatisch berechnet', verbose_name='Sortierbare Größe'),
        ),
        migrations.RunPython(forwards_func, reverse_func),
    ]
