# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-05 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0006_auto_20160830_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_at',
            field=models.DateField(blank=True, null=True, verbose_name='Ausgegeben am'),
        ),
    ]
