# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-14 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mgmt_comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='mgmt_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='room',
            name='mgmt_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='room',
            name='mgmt_source',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
