# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-24 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ophase',
            name='contact_email_address',
            field=models.CharField(default='ophase-leitung@fachschaft.informatik.tu-darmstadt.de', max_length=100, verbose_name='Kontaktadresse Leitung'),
            preserve_default=False,
        ),
    ]
