# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 19:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0003_auto_20160825_1424'),
        ('students', '0003_auto_20150913_1509'),
    ]

    operations = [
        migrations.CreateModel(
            name='OphaseActiveCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
            ],
            options={
                'ordering': ['ophase', 'category'],
                'verbose_name': 'Aktive Kategorie einer Ophase',
                'verbose_name_plural': 'Aktive Katgegorien einer Ophase',
            },
        ),
        migrations.CreateModel(
            name='OphaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description_template', models.CharField(max_length=50, verbose_name='Beschreibung in Template')),
                ('lang', models.CharField(default='de', max_length=5, verbose_name='Sprachcode')),
                ('priority', models.PositiveIntegerField(help_text='Die Priorität bestimmt unter anderem die Reihenfolge der Anzeige auf der Webseite', verbose_name='Priorität')),
            ],
            options={
                'ordering': ['priority'],
                'verbose_name': 'Art der Ophase',
                'verbose_name_plural': 'Arten der Ophase',
            },
        ),
        migrations.RemoveField(
            model_name='ophase',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ophase',
            name='start_date',
        ),
        migrations.AddField(
            model_name='ophase',
            name='name',
            field=models.CharField(default='Ophase', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ophaseactivecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophasebase.OphaseCategory', verbose_name='Art der Ophase'),
        ),
        migrations.AddField(
            model_name='ophaseactivecategory',
            name='ophase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Ophase', verbose_name='Ophase'),
        ),
        migrations.AddField(
            model_name='ophase',
            name='categories',
            field=models.ManyToManyField(related_name='ophase_categories', through='ophasebase.OphaseActiveCategory', to='ophasebase.OphaseCategory'),
        ),
    ]
