# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 14:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0003_auto_20160825_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='OphaseActiveCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_date', models.DateField(verbose_name='Beginn')),
                ('end_date', models.DateField(verbose_name='Ende')),
            ],
            options={
                'verbose_name_plural': 'Aktive Katgegorien einer Ophase',
                'verbose_name': 'Aktive Kategorie einer Ophase',
                'ordering': ['ophase', 'category'],
            },
        ),
        migrations.CreateModel(
            name='OphaseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('priority', models.PositiveIntegerField(help_text='Die Priorität bestimmt unter anderem die Reihenfolge der Anzeige auf der Webseite', verbose_name='Priorität')),
            ],
            options={
                'verbose_name_plural': 'Arten der Ophase',
                'verbose_name': 'Art der Ophase',
                'ordering': ['priority'],
            },
        ),
        migrations.AddField(
            model_name='ophaseactivecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophasebase.OphaseCategory', verbose_name='Art der Ophase'),
        ),
        migrations.AddField(
            model_name='ophaseactivecategory',
            name='ophase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Ophase', verbose_name='Ophase'),
        ),
    ]
