# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0004_auto_20170201_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ophase',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='ophase',
            name='start_date',
        ),
        migrations.AddField(
            model_name='ophase',
            name='categories',
            field=models.ManyToManyField(through='ophasebase.OphaseActiveCategory', to='ophasebase.OphaseCategory'),
        ),
    ]
