# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0004_auto_20170209_2025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ophasecategory',
            name='description_template',
        ),
        migrations.AddField(
            model_name='ophasecategory',
            name='slug',
            field=models.CharField(default='', max_length=25, verbose_name='URL Slug'),
            preserve_default=False,
        ),
    ]
