# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0004_auto_20170209_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='ophasecategory',
            name='details_template',
            field=models.CharField(default='', max_length=50, verbose_name='Template für Stundenplan View'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ophasecategory',
            name='details_url',
            field=models.CharField(default='', max_length=50, verbose_name='Link zum Stundenplan'),
            preserve_default=False,
        ),
    ]
