# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0005_auto_20170201_2219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ophaseactivecategory',
            old_name='begin_date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='ophase',
            name='name',
            field=models.CharField(default='Ophase', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ophase',
            name='categories',
            field=models.ManyToManyField(related_name='ophase_categories', through='ophasebase.OphaseActiveCategory', to='ophasebase.OphaseCategory'),
        ),
    ]
