# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:16
from __future__ import unicode_literals

from django.db import migrations

def gen_slug(apps, schema_editor):
    OphaseCategory = apps.get_model('ophasebase', 'OphaseCategory')
    for row in OphaseCategory.objects.all():
        row.slug = str(row.name).lower().replace(" ", "-")
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0005_auto_20170215_1416'),
    ]

    operations = [
            migrations.RunPython(gen_slug,
                reverse_code=migrations.RunPython.noop),
    ]
