# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0006_auto_20170201_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ophasecategory',
            name='description_template',
            field=models.CharField(default='website/description/empty.html', max_length=50, verbose_name='Beschreibung in Template'),
            preserve_default=False,
        ),
    ]
