# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0006_auto_20170215_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ophasecategory',
            name='slug',
            field=models.CharField(max_length=25, verbose_name='URL Slug',
                unique=True),
        ),

    ]
