# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 23:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0007_ophasecategory_description_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='ophasecategory',
            name='lang',
            field=models.CharField(default='de', max_length=5, verbose_name='Sprachcode'),
        ),
    ]
