# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('ophasebase', '0007_auto_20170215_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupNotificationFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50, verbose_name='Django App Name')),
                ('action', models.CharField(blank=True, default='', help_text='Generelle Aktion. Kann leer gelassen werden um alle Benachrichtigungen der APP zu empfangen', max_length=100, verbose_name='Aktion')),
                ('digest', models.BooleanField(default=False, verbose_name='Als Digest verschicken?')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
            options={
                'verbose_name': 'Benachrichtigungsfilter für Gruppe',
                'verbose_name_plural': 'Benachrichtigungsfilter für Gruppen',
                'ordering': ['group', 'app', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=50, verbose_name='Django App Name')),
                ('action', models.CharField(help_text='Generelle Aktion', max_length=100, verbose_name='Aktion')),
                ('event', models.TextField(help_text='Textuelle Beschreibung des genauen Ereignisses', verbose_name='Ereignis')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('detail_url', models.URLField(blank=True, default='', verbose_name='Detail URL')),
                ('icon', models.CharField(blank=True, default='', help_text='FA class (ohne fa-)', max_length=20, verbose_name='Icon (Font Awesome)')),
                ('digest_sent', models.BooleanField(default=False, help_text='Wurde diese Benachrichtigung bereits als Digest versandt?', verbose_name='Digest gesendet?')),
            ],
            options={
                'verbose_name': 'Benachrichtigung',
                'verbose_name_plural': 'Benachrichtigungen',
                'ordering': ['-timestamp'],
            },
        ),
    ]
