# Generated by Django 2.0.9 on 2018-10-05 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0007_auto_20170215_1416'),
    ]
    operations = [
        migrations.RunSQL("""DROP TABLE IF EXISTS `website_categorydetails`;"""),
        migrations.RunSQL("""DROP TABLE IF EXISTS `website_settings`;"""),
        migrations.RunSQL("""DROP TABLE IF EXISTS `website_oinforz`;"""),
    ]

