# Generated by Django 2.0.10 on 2019-02-26 17:53

from django.db import migrations, models

def update_dates(apps, schema_editor):
    OphaseActiveCategory = apps.get_model('ophasebase', 'OphaseActiveCategory')
    Ophase = apps.get_model('ophasebase', 'Ophase')

    for cu_op in Ophase.objects.all():
        dates = OphaseActiveCategory.objects.filter(ophase=cu_op).aggregate(start=models.Min('start_date'), end=models.Max('end_date'))
        cu_op.start_date_by_category = dates.get('start', None)
        cu_op.end_date_by_category = dates.get('end', None)
        cu_op.save()

class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0007_auto_20170215_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='ophase',
            name='end_date_by_category',
            field=models.DateField(blank=True, null=True, verbose_name='Ende'),
        ),
        migrations.AddField(
            model_name='ophase',
            name='start_date_by_category',
            field=models.DateField(blank=True, null=True, verbose_name='Beginn'),
        ),
        migrations.RunPython(update_dates, reverse_code=migrations.RunPython.noop),
    ]
