# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0018_person_tutor_experience'),
        ('ophasebase', '0007_auto_20170215_1416'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlotType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#FFFFFF', max_length=7)),
            ],
            options={
                'verbose_name_plural': 'Veranstaltungsarten',
                'verbose_name': 'Veranstaltungsart',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('begin', models.DateTimeField(verbose_name='Beginn')),
                ('end', models.DateTimeField(verbose_name='Ende')),
                ('attendance_required', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(to='ophasebase.OphaseCategory')),
                ('ophase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Ophase')),
                ('relevant_for', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.StaffFilterGroup', verbose_name='Filterkriterium: Wer muss anwesend sein?')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophasebase.Room', verbose_name='Raum')),
                ('slottype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.SlotType')),
            ],
            options={
                'verbose_name_plural': 'Zeitslots',
                'verbose_name': 'Zeitslot',
                'ordering': ['begin'],
            },
        ),
    ]
