# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0018_person_tutor_experience'),
        ('ophasebase', '0007_auto_20170215_1416'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ophasebase.Room', verbose_name='Raum')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.RemoveField(
            model_name='timeslot',
            name='room',
        ),
        migrations.AddField(
            model_name='event',
            name='timeslot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.TimeSlot', verbose_name='Zeitslot'),
        ),
        migrations.AddField(
            model_name='event',
            name='tutorgroup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.TutorGroup', verbose_name='Kleingruppe'),
        ),
        migrations.AlterUniqueTogether(
            name='event',
            unique_together=set([('timeslot', 'tutorgroup')]),
        ),
    ]
