# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ophasebase', '0007_auto_20170215_1416'),
        ('plan', '0002_auto_20170410_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateTimeField(verbose_name='Anfang')),
                ('end', models.DateTimeField(verbose_name='Ende')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Gebucht'), (2, 'Blockiert'), (3, 'Anfragen?'), (4, 'Angefragt'), (5, 'Überlappung')])),
                ('comment', models.TextField(blank=True, verbose_name='Kommentar')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ophasebase.Room', verbose_name='Raum')),
            ],
            options={
                'verbose_name': 'Raumbuchung',
                'verbose_name_plural': 'Raumbuchungen',
            },
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='relevant_for',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.StaffFilterGroup', verbose_name='Filterkriterium: Wer könnte anwesend sein?'),
        ),
    ]
