# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_auto_20170410_1825'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['room', '-begin'], 'verbose_name': 'Raumbuchung', 'verbose_name_plural': 'Raumbuchungen'},
        ),
    ]
