# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-13 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20170410_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='slottype',
            name='split_groups',
            field=models.BooleanField(default=False, verbose_name='In Kleingruppen aufteilen?'),
        ),
        migrations.AlterField(
            model_name='timeslot',
            name='relevant_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.StaffFilterGroup', verbose_name='Filterkriterium: Wer könnte anwesend sein?'),
        ),
    ]
